version: '3.8'

services:
  # Servicio de tu aplicación .NET
  nutritional-delibery: 
    image: stephaniheredia/microservicio-nutritional-delibery:latest
    container_name: nutritional-delibery
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=nutritionalDelibery;Username=postgres;Password=password
      - RabbitMqSettings__Host=rabbitmq
      - RabbitMqSettings__UserName=storeUser
      - RabbitMqSettings__Password=storeUserPassword
      - RabbitMqSettings__VirtualHost=/
    ports:
      - 5085:5085  
    depends_on:
      - postgres-db
    networks:
      - nur-network 
      - kong-net
  # Servicio de la base de datos postgresql
  postgres-db: 
    image: stephaniheredia/nutritionaldeliberydb:latest
    container_name: nutritionaldelibery-db 
    environment:
      - POSTGRES_DB=nutritionalDelibery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password 
    ports:
      - 5445:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nutritionalDelibery"]
      interval: 10s
      retries: 5
      start_period: 20s
    networks:
      - nur-network 

networks:
  nur-network:
    external: true  
  kong-net:
    external: true  

volumes:
  postgres_data:
