// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutritionalDelibery.Infrastructure.DomainModel;

#nullable disable

namespace NutritionalDelibery.Infrastructure.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20250704054007_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutritionalDelibery.Domain.DeliveryNote.DeliveryNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeliveryDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ImagePath");

                    b.Property<Guid>("PacientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PacientId");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.ToTable("DeliveryNote", (string)null);
                });

            modelBuilder.Entity("NutritionalDelibery.Domain.DeliveryRoute.DeliveryRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<double>("LatitudeDestination")
                        .HasColumnType("double precision")
                        .HasColumnName("LatitudeDestination");

                    b.Property<double>("LatitudeOrigin")
                        .HasColumnType("double precision")
                        .HasColumnName("LatitudeOrigin");

                    b.Property<double>("LongitudeDestination")
                        .HasColumnType("double precision")
                        .HasColumnName("LongitudeDestination");

                    b.Property<double>("LongitudeOrigin")
                        .HasColumnType("double precision")
                        .HasColumnName("LongitudeOrigin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("DeliveryRoute", (string)null);
                });

            modelBuilder.Entity("NutritionalDelibery.Domain.ExitNote.ExitNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("DeliveryPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeliveryPersonId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<DateTime>("ExitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExitDate");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("Number");

                    b.HasKey("Id");

                    b.ToTable("ExitNote", (string)null);
                });

            modelBuilder.Entity("NutritionalDelibery.Domain.ExitNoteDetail.ExitNoteDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("ExitNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ExitNoteId");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("PackageId");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.HasKey("Id");

                    b.ToTable("ExitNoteDetail", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
